$(PWD)/table_process_main/$(TARGET):$(OBJ2)
	$(CC) $(DEBUG) $(CXXFLAGS) $@ $^ $(INCLUDE_DIR)  $(LD_DIR)  $(LD) 
$(PWD)/table_process_main/src/%.o:$(PWD)/table_process_main/src/%.cpp
	$(CC) $(DEBUG) $(CXXFLAGS) $@ -c $^ $(INCLUDE_DIR) 
